"""courses feature: course, course_category, course_page, course_page_attachment.

The feature's first revision, so it chains from nothing and owns its own
alembic_splent_feature_courses version table.

Written by hand rather than autogenerated, because the visibility columns
arrive through VisibilityMixin and are the ones that must not be wrong.
``hidden`` carries a server default so a row inserted by anything other
than the ORM is visible only if it says so, and ``publish_at`` is indexed
on all three levels because every listing asks about it.

Revision ID: courses0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "courses0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "course",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        # The cover lives in the media library. Deliberately not a foreign
        # key, so courses do not need that table to exist.
        sa.Column("cover_media_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hidden", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_course_slug"), "course", ["slug"], unique=True)
    op.create_index(
        op.f("ix_course_publish_at"), "course", ["publish_at"], unique=False
    )

    op.create_table(
        "course_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("hidden", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["course.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # Slugs repeat across years, so they are unique within a course
        # and not beyond it.
        sa.UniqueConstraint("course_id", "slug", name="uq_category_slug"),
    )
    op.create_index(
        op.f("ix_course_category_course_id"),
        "course_category",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_category_publish_at"),
        "course_category",
        ["publish_at"],
        unique=False,
    )

    op.create_table(
        "course_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        # What this page was called in the wiki it came from, so links
        # written years ago keep resolving.
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hidden", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["course.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["category_id"], ["course_category.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "slug", name="uq_page_slug"),
    )
    op.create_index(
        op.f("ix_course_page_course_id"), "course_page", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_page_category_id"), "course_page", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_page_legacy_id"), "course_page", ["legacy_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_page_publish_at"), "course_page", ["publish_at"], unique=False
    )

    op.create_table(
        "course_page_attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        # The bytes live in the media library as a restricted item. Not a
        # foreign key, so the access resolver is what ties the two
        # together and media can be replaced without a schema change.
        sa.Column("media_item_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["page_id"], ["course_page.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_page_attachment_page_id"),
        "course_page_attachment",
        ["page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_page_attachment_media_item_id"),
        "course_page_attachment",
        ["media_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_page_attachment_legacy_id"),
        "course_page_attachment",
        ["legacy_id"],
        unique=False,
    )


def downgrade():
    op.drop_index(
        op.f("ix_course_page_attachment_legacy_id"),
        table_name="course_page_attachment",
    )
    op.drop_index(
        op.f("ix_course_page_attachment_media_item_id"),
        table_name="course_page_attachment",
    )
    op.drop_index(
        op.f("ix_course_page_attachment_page_id"), table_name="course_page_attachment"
    )
    op.drop_table("course_page_attachment")

    op.drop_index(op.f("ix_course_page_publish_at"), table_name="course_page")
    op.drop_index(op.f("ix_course_page_legacy_id"), table_name="course_page")
    op.drop_index(op.f("ix_course_page_category_id"), table_name="course_page")
    op.drop_index(op.f("ix_course_page_course_id"), table_name="course_page")
    op.drop_table("course_page")

    op.drop_index(op.f("ix_course_category_publish_at"), table_name="course_category")
    op.drop_index(op.f("ix_course_category_course_id"), table_name="course_category")
    op.drop_table("course_category")

    op.drop_index(op.f("ix_course_publish_at"), table_name="course")
    op.drop_index(op.f("ix_course_slug"), table_name="course")
    op.drop_table("course")
